apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/argoproj-labs/argocd-ephemeral-access/releases/download/v0.1.5-rc2/install.yaml

components:
  - ./plugin
